# Generated by Django 3.0.2 on 2020-01-20 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='url',
        ),
    ]
